version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - "3000:3000"
    
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: "mongodb://db:27017/animals_db"

    depends_on:
      - db
    
    restart: unless-stopped

  db:
    image: mongo:6
    
    ports:
      - "27017:27017"
    
    volumes:
      - db_data:/data/db
      
    restart: unless-stopped

volumes:
  db_data: